# Generated by Django 3.0.1 on 2021-07-08 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExceptionType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exception_ID', models.IntegerField()),
                ('exception_name', models.CharField(max_length=50)),
                ('exception_description', models.CharField(max_length=50)),
                ('exception_component', models.CharField(max_length=20)),
                ('exception_level', models.CharField(max_length=20)),
            ],
        ),
    ]
